on:
  workflow_dispatch:
jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old test images
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: snok
          token: ${{ secrets.PAT }}
          image-names: "test"
          image-tags: "0.2"
          cut-off: 1s
          dry-run: true
